/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from "@tanstack/react-router"

// Import Routes

import { Route as rootRoute } from "./routes/__root"
import { Route as LayoutImport } from "./routes/_layout"
import { Route as LayoutIndexImport } from "./routes/_layout/index"
import { Route as AuthAuthLayoutImport } from "./routes/auth/_auth-layout"
import { Route as AuthAuthLayoutIndexImport } from "./routes/auth/_auth-layout/index"
import { Route as LayoutUsersIndexImport } from "./routes/_layout/users/index"
import { Route as LayoutTestIndexImport } from "./routes/_layout/test/index"
import { Route as LayoutStatisticIndexImport } from "./routes/_layout/statistic/index"
import { Route as LayoutExamIndexImport } from "./routes/_layout/exam/index"
import { Route as AuthAuthLayoutRegisterImport } from "./routes/auth/_auth-layout/register"
import { Route as AuthAuthLayoutLoginImport } from "./routes/auth/_auth-layout/login"
import { Route as LayoutUsersUserIdImport } from "./routes/_layout/users/$userId"
import { Route as LayoutExamExamidImport } from "./routes/_layout/exam/$exam_id"
import { Route as LayoutTestTestIdIndexImport } from "./routes/_layout/test/$testId/index"

// Create Virtual Routes

const AuthImport = createFileRoute("/auth")()

// Create/Update Routes

const AuthRoute = AuthImport.update({
  id: "/auth",
  path: "/auth",
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: "/_layout",
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => LayoutRoute,
} as any)

const AuthAuthLayoutRoute = AuthAuthLayoutImport.update({
  id: "/_auth-layout",
  getParentRoute: () => AuthRoute,
} as any)

const AuthAuthLayoutIndexRoute = AuthAuthLayoutIndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthAuthLayoutRoute,
} as any)

const LayoutUsersIndexRoute = LayoutUsersIndexImport.update({
  id: "/users/",
  path: "/users/",
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutTestIndexRoute = LayoutTestIndexImport.update({
  id: "/test/",
  path: "/test/",
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutStatisticIndexRoute = LayoutStatisticIndexImport.update({
  id: "/statistic/",
  path: "/statistic/",
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutExamIndexRoute = LayoutExamIndexImport.update({
  id: "/exam/",
  path: "/exam/",
  getParentRoute: () => LayoutRoute,
} as any)

const AuthAuthLayoutRegisterRoute = AuthAuthLayoutRegisterImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => AuthAuthLayoutRoute,
} as any)

const AuthAuthLayoutLoginRoute = AuthAuthLayoutLoginImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => AuthAuthLayoutRoute,
} as any)

const LayoutUsersUserIdRoute = LayoutUsersUserIdImport.update({
  id: "/users/$userId",
  path: "/users/$userId",
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutExamExamidRoute = LayoutExamExamidImport.update({
  id: "/exam/$exam_id",
  path: "/exam/$exam_id",
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutTestTestIdIndexRoute = LayoutTestTestIdIndexImport.update({
  id: "/test/$testId/",
  path: "/test/$testId/",
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_layout": {
      id: "/_layout"
      path: ""
      fullPath: ""
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    "/auth": {
      id: "/auth"
      path: "/auth"
      fullPath: "/auth"
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    "/auth/_auth-layout": {
      id: "/auth/_auth-layout"
      path: "/auth"
      fullPath: "/auth"
      preLoaderRoute: typeof AuthAuthLayoutImport
      parentRoute: typeof AuthRoute
    }
    "/_layout/": {
      id: "/_layout/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    "/_layout/exam/$exam_id": {
      id: "/_layout/exam/$exam_id"
      path: "/exam/$exam_id"
      fullPath: "/exam/$exam_id"
      preLoaderRoute: typeof LayoutExamExamidImport
      parentRoute: typeof LayoutImport
    }
    "/_layout/users/$userId": {
      id: "/_layout/users/$userId"
      path: "/users/$userId"
      fullPath: "/users/$userId"
      preLoaderRoute: typeof LayoutUsersUserIdImport
      parentRoute: typeof LayoutImport
    }
    "/auth/_auth-layout/login": {
      id: "/auth/_auth-layout/login"
      path: "/login"
      fullPath: "/auth/login"
      preLoaderRoute: typeof AuthAuthLayoutLoginImport
      parentRoute: typeof AuthAuthLayoutImport
    }
    "/auth/_auth-layout/register": {
      id: "/auth/_auth-layout/register"
      path: "/register"
      fullPath: "/auth/register"
      preLoaderRoute: typeof AuthAuthLayoutRegisterImport
      parentRoute: typeof AuthAuthLayoutImport
    }
    "/_layout/exam/": {
      id: "/_layout/exam/"
      path: "/exam"
      fullPath: "/exam"
      preLoaderRoute: typeof LayoutExamIndexImport
      parentRoute: typeof LayoutImport
    }
    "/_layout/statistic/": {
      id: "/_layout/statistic/"
      path: "/statistic"
      fullPath: "/statistic"
      preLoaderRoute: typeof LayoutStatisticIndexImport
      parentRoute: typeof LayoutImport
    }
    "/_layout/test/": {
      id: "/_layout/test/"
      path: "/test"
      fullPath: "/test"
      preLoaderRoute: typeof LayoutTestIndexImport
      parentRoute: typeof LayoutImport
    }
    "/_layout/users/": {
      id: "/_layout/users/"
      path: "/users"
      fullPath: "/users"
      preLoaderRoute: typeof LayoutUsersIndexImport
      parentRoute: typeof LayoutImport
    }
    "/auth/_auth-layout/": {
      id: "/auth/_auth-layout/"
      path: "/"
      fullPath: "/auth/"
      preLoaderRoute: typeof AuthAuthLayoutIndexImport
      parentRoute: typeof AuthAuthLayoutImport
    }
    "/_layout/test/$testId/": {
      id: "/_layout/test/$testId/"
      path: "/test/$testId"
      fullPath: "/test/$testId"
      preLoaderRoute: typeof LayoutTestTestIdIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutExamExamidRoute: typeof LayoutExamExamidRoute
  LayoutUsersUserIdRoute: typeof LayoutUsersUserIdRoute
  LayoutExamIndexRoute: typeof LayoutExamIndexRoute
  LayoutStatisticIndexRoute: typeof LayoutStatisticIndexRoute
  LayoutTestIndexRoute: typeof LayoutTestIndexRoute
  LayoutUsersIndexRoute: typeof LayoutUsersIndexRoute
  LayoutTestTestIdIndexRoute: typeof LayoutTestTestIdIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutExamExamidRoute: LayoutExamExamidRoute,
  LayoutUsersUserIdRoute: LayoutUsersUserIdRoute,
  LayoutExamIndexRoute: LayoutExamIndexRoute,
  LayoutStatisticIndexRoute: LayoutStatisticIndexRoute,
  LayoutTestIndexRoute: LayoutTestIndexRoute,
  LayoutUsersIndexRoute: LayoutUsersIndexRoute,
  LayoutTestTestIdIndexRoute: LayoutTestTestIdIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface AuthAuthLayoutRouteChildren {
  AuthAuthLayoutLoginRoute: typeof AuthAuthLayoutLoginRoute
  AuthAuthLayoutRegisterRoute: typeof AuthAuthLayoutRegisterRoute
  AuthAuthLayoutIndexRoute: typeof AuthAuthLayoutIndexRoute
}

const AuthAuthLayoutRouteChildren: AuthAuthLayoutRouteChildren = {
  AuthAuthLayoutLoginRoute: AuthAuthLayoutLoginRoute,
  AuthAuthLayoutRegisterRoute: AuthAuthLayoutRegisterRoute,
  AuthAuthLayoutIndexRoute: AuthAuthLayoutIndexRoute,
}

const AuthAuthLayoutRouteWithChildren = AuthAuthLayoutRoute._addFileChildren(
  AuthAuthLayoutRouteChildren,
)

interface AuthRouteChildren {
  AuthAuthLayoutRoute: typeof AuthAuthLayoutRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAuthLayoutRoute: AuthAuthLayoutRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  "": typeof LayoutRouteWithChildren
  "/auth": typeof AuthAuthLayoutRouteWithChildren
  "/": typeof LayoutIndexRoute
  "/exam/$exam_id": typeof LayoutExamExamidRoute
  "/users/$userId": typeof LayoutUsersUserIdRoute
  "/auth/login": typeof AuthAuthLayoutLoginRoute
  "/auth/register": typeof AuthAuthLayoutRegisterRoute
  "/exam": typeof LayoutExamIndexRoute
  "/statistic": typeof LayoutStatisticIndexRoute
  "/test": typeof LayoutTestIndexRoute
  "/users": typeof LayoutUsersIndexRoute
  "/auth/": typeof AuthAuthLayoutIndexRoute
  "/test/$testId": typeof LayoutTestTestIdIndexRoute
}

export interface FileRoutesByTo {
  "/auth": typeof AuthAuthLayoutIndexRoute
  "/": typeof LayoutIndexRoute
  "/exam/$exam_id": typeof LayoutExamExamidRoute
  "/users/$userId": typeof LayoutUsersUserIdRoute
  "/auth/login": typeof AuthAuthLayoutLoginRoute
  "/auth/register": typeof AuthAuthLayoutRegisterRoute
  "/exam": typeof LayoutExamIndexRoute
  "/statistic": typeof LayoutStatisticIndexRoute
  "/test": typeof LayoutTestIndexRoute
  "/users": typeof LayoutUsersIndexRoute
  "/test/$testId": typeof LayoutTestTestIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  "/_layout": typeof LayoutRouteWithChildren
  "/auth": typeof AuthRouteWithChildren
  "/auth/_auth-layout": typeof AuthAuthLayoutRouteWithChildren
  "/_layout/": typeof LayoutIndexRoute
  "/_layout/exam/$exam_id": typeof LayoutExamExamidRoute
  "/_layout/users/$userId": typeof LayoutUsersUserIdRoute
  "/auth/_auth-layout/login": typeof AuthAuthLayoutLoginRoute
  "/auth/_auth-layout/register": typeof AuthAuthLayoutRegisterRoute
  "/_layout/exam/": typeof LayoutExamIndexRoute
  "/_layout/statistic/": typeof LayoutStatisticIndexRoute
  "/_layout/test/": typeof LayoutTestIndexRoute
  "/_layout/users/": typeof LayoutUsersIndexRoute
  "/auth/_auth-layout/": typeof AuthAuthLayoutIndexRoute
  "/_layout/test/$testId/": typeof LayoutTestTestIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ""
    | "/auth"
    | "/"
    | "/exam/$exam_id"
    | "/users/$userId"
    | "/auth/login"
    | "/auth/register"
    | "/exam"
    | "/statistic"
    | "/test"
    | "/users"
    | "/auth/"
    | "/test/$testId"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/auth"
    | "/"
    | "/exam/$exam_id"
    | "/users/$userId"
    | "/auth/login"
    | "/auth/register"
    | "/exam"
    | "/statistic"
    | "/test"
    | "/users"
    | "/test/$testId"
  id:
    | "__root__"
    | "/_layout"
    | "/auth"
    | "/auth/_auth-layout"
    | "/_layout/"
    | "/_layout/exam/$exam_id"
    | "/_layout/users/$userId"
    | "/auth/_auth-layout/login"
    | "/auth/_auth-layout/register"
    | "/_layout/exam/"
    | "/_layout/statistic/"
    | "/_layout/test/"
    | "/_layout/users/"
    | "/auth/_auth-layout/"
    | "/_layout/test/$testId/"
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout",
        "/auth"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/",
        "/_layout/exam/$exam_id",
        "/_layout/users/$userId",
        "/_layout/exam/",
        "/_layout/statistic/",
        "/_layout/test/",
        "/_layout/users/",
        "/_layout/test/$testId/"
      ]
    },
    "/auth": {
      "filePath": "auth",
      "children": [
        "/auth/_auth-layout"
      ]
    },
    "/auth/_auth-layout": {
      "filePath": "auth/_auth-layout.tsx",
      "parent": "/auth",
      "children": [
        "/auth/_auth-layout/login",
        "/auth/_auth-layout/register",
        "/auth/_auth-layout/"
      ]
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/exam/$exam_id": {
      "filePath": "_layout/exam/$exam_id.tsx",
      "parent": "/_layout"
    },
    "/_layout/users/$userId": {
      "filePath": "_layout/users/$userId.tsx",
      "parent": "/_layout"
    },
    "/auth/_auth-layout/login": {
      "filePath": "auth/_auth-layout/login.tsx",
      "parent": "/auth/_auth-layout"
    },
    "/auth/_auth-layout/register": {
      "filePath": "auth/_auth-layout/register.tsx",
      "parent": "/auth/_auth-layout"
    },
    "/_layout/exam/": {
      "filePath": "_layout/exam/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/statistic/": {
      "filePath": "_layout/statistic/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/test/": {
      "filePath": "_layout/test/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/users/": {
      "filePath": "_layout/users/index.tsx",
      "parent": "/_layout"
    },
    "/auth/_auth-layout/": {
      "filePath": "auth/_auth-layout/index.tsx",
      "parent": "/auth/_auth-layout"
    },
    "/_layout/test/$testId/": {
      "filePath": "_layout/test/$testId/index.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
